"""expand_documents_schema

Revision ID: d94445a65a2e
Revises: e5b807d98da0
Create Date: 2026-08-30 19:35:59.486791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94445a65a2e'
down_revision: Union[str, Sequence[str], None] = 'e5b807d98da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('file_type', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('file_size', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'owner_id')
    op.drop_column('documents', 'file_hash')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
